# resources
cuda: true
compile: true
cudagraphs: false

# env
sync_vec_env: true
num_env: 8
action_repeat: 1
capture_video: false

# logging
wandb_project: "calico"
measure_burnin: 3

# training mode
num_timesteps: 10000000
learning_starts: 5000
training_steps_per_iter: 1
eval_steps: 10
eval_every: 2000

# evaluation mode
num_episodes: 10
gather_trajectories: false

# model
batch_norm: true
layer_norm: false

# optimization
actor_lr: 3e-4
crit_lr: 1e-3
clip_norm: 0.

# algorithm
segment_len: 1
batch_size: 256
gamma: 0.99
rb_capacity: 1000000
polyak: 0.005
prefer_td3_over_sac: false
bcq_style_targ_mix: false
actor_update_delay: true
crit_targ_update_freq: 1
alpha_init: 0.2
autotune: true
log_alpha_lr: 1e-3
