# resources
cuda: true
fp16: false

# env
vectorized: true
multi_proc: true
numenv: 8
horizon: 1000
action_repeat: 1
ini_rando_steps: 25000

# logging
wandb_project: "calico"

# training mode
learning_starts: 5000
num_timesteps: 3000000
training_steps_per_iter: 1
eval_steps_per_iter: 10
eval_every: 100

# evaluation mode
num_episodes: 10
render: false
gather: false
record: false

# model
batch_norm: true
layer_norm: false

# optimization
actr_lr: 3e-4
crit_lr: 3e-4
clip_norm: 0.

# algorithm
segment_len: 1
batch_size: 256
gamma: 0.99
rbx_capacity: 1000000
polyak: 0.005
use_mish_over_relu: true
prefer_td3_over_sac: false
bcq_style_targ_mix: false
actr_update_delay: false
crit_targ_update_freq: 2
alpha_init: 0.1
learnable_alpha: true
log_alpha_lr: 3e-4
state_dependent_std: true
