# resources
cuda: true

# env
sync_vec_env: true
num_env: 8
action_repeat: 1
capture_video: false

# logging
wandb_project: "calico"
measure_burnin: 3

# training mode
num_timesteps: 10000000
learning_starts: 25000
training_steps_per_iter: 1
eval_steps: 10
eval_every: 2000

# evaluation mode
num_episodes: 10
gather_trajectories: false

# model
batch_norm: true
layer_norm: false

# optimization
actor_lr: 3e-4
crit_lr: 3e-4
clip_norm: 0.

# algorithm
segment_len: 1
batch_size: 256
gamma: 0.99
rbx_capacity: 1000000
polyak: 0.005
prefer_td3_over_sac: true
bcq_style_targ_mix: true
actor_update_delay: true
actor_noise_std: 0.1
targ_actor_smoothing: true
td3_std: 0.2
td3_c: 0.5
